[build]
  base    = "eq-author"
  publish = "eq-author/build"
  command = "yarn build"

[context.branch-deploy]
   environment = { REACT_APP_API_URL = "https://prototype-units.ngrok.io/graphql" }

[context.production]
  environment = { REACT_APP_API_URL = "https://prototype-units.ngrok.io/graphql" }