name: Codecov workflow

on: [push, pull_request]

jobs:
  author-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Generate coverage report
        run: |
          cd eq-author
          yarn install --frozen-lockfile
          yarn test --coverage
        env:
          CI: true
      - name: Coverage
        uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: eq-author/coverage/coverage-final.json
          flags: author
          name: eq-author
  publisher-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Generate coverage report
        run: |
          cd eq-publisher
          yarn install --frozen-lockfile
          yarn test --coverage
        env:
          CI: true
      - name: Coverage
        uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: eq-publisher/coverage/coverage-final.json
          flags: publisher
          name: eq-publisher
